### ISSUE TITLE
StartMenu Directory Name

### ISSUE THREAD

**Issue by MTRNord** [mongodb-js/electron-squirrel-startup#14]
I use electron-builder for my builds and wan't that the StartMenu Folder is named like the App itself but it always uses the Author field. Is there a way to change it?

**Comment by develar** [comment]
It is how Squirrel.Windows works. It is not this module task. You can try to use NSIS target.

**Comment by develar** [comment]
As a dirty solution you can set author name to app name, see electron-builder options.
