### ISSUE TITLE
SyntaxError: 'return' outside of function

### ISSUE THREAD

**Issue by matthiaslau** [mongodb-js/electron-squirrel-startup#15]
The node parser doesn´t allow 'return' outside of a function (see https://github.com/nodejs/node-v0.x-archive/issues/6254) and throws `SyntaxError: 'return' outside of function`.

When I get this right it is necessary to have a `return` at the beginning of the main.js. Is there a solution for this?

**Comment by matthiaslau** [comment]
Using `app.quit()'` instead of `return` is also working, perhaps it is helpful to add this to the README :-D

**Comment by durran** [comment]
Added to README courtesy of @nimerix . Thanks for the report.
