### ISSUE TITLE
Bad shortcut name

### ISSUE THREAD

**Issue by bitomule** [mongodb-js/electron-squirrel-startup#2]
I'm using this package with https://github.com/atom/grunt-electron-installer but the start menu app name is wrong. It says "Electron" and not my app name. How do I change that name, where does squirrel-startup takes the name from?

Thanks!

**Comment by bitomule** [comment]
Sorry, I think it's an issue with electron-packager.

**Comment by imlucas** [comment]
@bitomule np :wave:

**Comment by jg123** [comment]
In case anyone else ends up here and is looking for the answer:
You must set the --version-string.ProductName parameter of electron-packager. If using gulp or grunt to build, you will need something like this:
'version-string': {
ProductName: 'Your App'
}
