### ISSUE TITLE
Squirrel triggering virustotal "PUA.Shopper"?

### ISSUE THREAD

**Issue by dimino** [mongodb-js/electron-squirrel-startup#26]
Based on this comment:

https://github.com/dustinblackman/Championify/issues/244#issuecomment-269629375

Is this true?  Trying to track down a flag in a recent Virustotal hit on the above project.

Is there a way for that project to avoid the flag?

**Comment by imlucas** [comment]
See Squirrel.Windows https://github.com/Squirrel/Squirrel.Windows/issues/786#issuecomment-237299772
