### ISSUE TITLE
core.require is not a function

### ISSUE THREAD

**Issue by mzmousa** [mongodb-js/electron-squirrel-startup#5]
I added the line `if (require ('electron-squirrel-startup')) return;`
to the top of my electron app. I have all the required dependencies installed. However, I keep getting the error

```
TypeError: core.require is not a function
```

I am running electron v0.37.8 on a Windows 7 machine, node v.6.1.0 and npm v.3.8.9.

**Comment by mzmousa** [comment]
@plrthink have you ever come across this issue / know a fix for it? :)

**Comment by plrthink** [comment]
not sure why this would happen? Everythings works fine for me on windows 10 with electron 0.36.6. I find this (https://discuss.atom.io/t/first-launch-of-electron/17511/2), hope it would be helpful.

**Comment by mzmousa** [comment]
Still nothing :cry: I removed the `node_modules` directory within `electron-squirrel-startup` and then did another `npm install` to no success. It's not so urgent for me anymore as I've figured out how to handle squirrel events myself, but it would still be nice if I knew the reason for this happening.

**Comment by imlucas** [comment]
note the errant space after `require`

```
if (require ('electron-squirrel-startup')) return;
```

**Comment by mzmousa** [comment]
I have literally never come across that before. Fuck, that makes me so mad, literally a space has driven me bat-shit crazy.
Anyways, it works now, thank you so much :smile:
