### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by nickdima** [mongodb-js/electron-squirrel-startup#7]
What's the use case for this? Using electron's `autoUpdater` module is not enough for Windows?
Just trying to figure out if I need this or not...

**Comment by develar** [comment]
You should [handle Squirrel events](https://github.com/electron/windows-installer#handling-squirrel-events). This module helps you to do it.

**Comment by nickdima** [comment]
Got it! Thanks!

**Comment by develar** [comment]
FYI: electron-builder will soon support NSIS target to avoid such issues (i.e. you will be not forced to handle such events).

**Comment by nickdima** [comment]
OK, I'll keep an eye on that.
